<a href="https://colab.research.google.com/github/asadian98/Deep-Learning-Course-EE25647/blob/HW3%2FQ1%2FPreprocessing/HW3/HW3_Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
%cd drive/MyDrive/

/content/drive/MyDrive

In [4]:
!unzip trainingandtestdata.zip

Archive:  trainingandtestdata.zip
  inflating: testdata.manual.2009.06.14.csv
  inflating: training.1600000.processed.noemoticon.csv

In [71]:
import pandas as pd
df = pd.read_csv('training.1600000.processed.noemoticon.csv', encoding = 'latin', header = None)
df.head(8)

   0  ...                                                  5
0  0  ...  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1  0  ...  is upset that he can't update his Facebook by ...
2  0  ...  @Kenichan I dived many times for the ball. Man...
3  0  ...    my whole body feels itchy and like its on fire
4  0  ...  @nationwideclass no, it's not behaving at all....
5  0  ...                      @Kwesidei not the whole crew
6  0  ...                                        Need a hug
7  0  ...  @LOLTrish hey  long time no see! Yes.. Rains a...

[8 rows x 6 columns]

In [72]:
# drop unnecessary columns 
df = df.drop([1, 2, 3, 4], axis=1)
# add header
df.columns = ['Label', 'Text']
df.head(8)

   Label                                               Text
0      0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1      0  is upset that he can't update his Facebook by ...
2      0  @Kenichan I dived many times for the ball. Man...
3      0    my whole body feels itchy and like its on fire
4      0  @nationwideclass no, it's not behaving at all....
5      0                      @Kwesidei not the whole crew
6      0                                        Need a hug
7      0  @LOLTrish hey  long time no see! Yes.. Rains a...

In [73]:
print(df.Label.value_counts()) # classes are balance

4    800000
0    800000
Name: Label, dtype: int64

In [74]:
df.Label[df.Label == 0] = "Negative"
df.Label[df.Label == 4] = "Positive"
df.head(8)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

      Label                                               Text
0  Negative  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1  Negative  is upset that he can't update his Facebook by ...
2  Negative  @Kenichan I dived many times for the ball. Man...
3  Negative    my whole body feels itchy and like its on fire
4  Negative  @nationwideclass no, it's not behaving at all....
5  Negative                      @Kwesidei not the whole crew
6  Negative                                        Need a hug
7  Negative  @LOLTrish hey  long time no see! Yes.. Rains a...

In [79]:
import nltk 
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [76]:
import re

def preprocessing(txt):
  txt = re.sub("#[A-Za-z0-9_]+","", str(txt).lower()).strip() # remove hashtag
  txt = re.sub("@[A-Za-z0-9_]+","", txt) # remove mentions
  txt = re.sub(r"http\S+", "", txt) # remove links
  txt = re.sub(r"www.\S+", "", txt) # remove links
  txt = re.sub('[()!?]', ' ', txt)  # remove punctuations
  txt = re.sub('\[.*?\]',' ', txt)  # remove punctuations
  txt = re.sub("[^a-z0-9]"," ", txt)# non-alphanumeric characters
  tweet = [word for word in txt.split() if word not in stop_words]
  return " ".join(tweet) 

df.Text = df.Text.apply(lambda x: preprocessing(x))

df.head(8)

      Label                                               Text
0  Negative       awww bummer shoulda got david carr third day
1  Negative  upset update facebook texting might cry result...
2  Negative  dived many times ball managed save 50 rest go ...
3  Negative                   whole body feels itchy like fire
4  Negative                                   behaving mad see
5  Negative                                         whole crew
6  Negative                                           need hug
7  Negative  hey long time see yes rains bit bit lol fine t...